import type { Line } from '../lineTypes';

/** Lines for Lantern Trail adventures 2–4. Short, specific, lightly funny; characters ask, decline, apologise and help. */

export const BRIDGE_LINES = {
  'rowan.hook': { speaker: 'rowan', text: 'Oh no — the bridge washed away! The picnic is on the other side.', mood: 'worried' },
  'moss.need': { speaker: 'moss', text: 'I can’t do steps. I need a flat way, nice and slow.', mood: 'calm' },
  'fizz.need': { speaker: 'fizz', text: 'Stepping stones! I want to hop across!', mood: 'excited' },
  'rowan.need': { speaker: 'rowan', text: 'My wagon needs something wide and steady.', mood: 'thinking' },
  'nar.gather': { speaker: 'narrator', text: 'Find planks and stones. Tap one to pick it up, then tap where it goes.', mood: 'happy' },
  'nar.carryPlank': { speaker: 'narrator', text: 'Now tap a plank spot across the stream.', mood: 'happy' },
  'nar.carryStone': { speaker: 'narrator', text: 'Now tap a stone spot in the water.', mood: 'happy' },
  'nar.wrongSpot': { speaker: 'narrator', text: 'That one goes in a different spot.', mood: 'thinking' },
  'nar.handsFull': { speaker: 'narrator', text: 'Your hands are full! Put this one down first.', mood: 'thinking' },
  'nar.found': { speaker: 'narrator', text: 'A plank under the leaves!', mood: 'surprised' },
  'fizz.floats': { speaker: 'fizz', text: 'Whoa! The plank is floating away!', mood: 'surprised' },
  'moss.tieIdea': { speaker: 'moss', text: 'Hmm. If we tie the planks together, they won’t float off.', mood: 'thinking' },
  'nar.fishIt': { speaker: 'narrator', text: 'Grab the long stick to fish the plank back.', mood: 'happy' },
  'nar.fished': { speaker: 'narrator', text: 'Got it! Back on the bank.', mood: 'excited' },
  'nar.tieIt': { speaker: 'narrator', text: 'Tap the rope to tie the planks.', mood: 'happy' },
  'moss.tied': { speaker: 'moss', text: 'Snug as a knot. Thank you for trying my idea.', mood: 'happy' },
  'rowan.wobbly': { speaker: 'rowan', text: 'It wobbles under my wagon. Could the planks be tied?', mood: 'worried' },
  'moss.noFlat': { speaker: 'moss', text: 'Those are steps for me. A flat way would help.', mood: 'calm' },
  'fizz.gap': { speaker: 'fizz', text: 'There’s still a gap! Even I can’t hop that far.', mood: 'silly' },
  'rowan.gap': { speaker: 'rowan', text: 'Not across yet — there’s a gap.', mood: 'thinking' },
  'moss.cross': { speaker: 'moss', text: 'Flat and slow. Perfect.', mood: 'happy' },
  'fizz.hop': { speaker: 'fizz', text: 'Hop! Hop! Hop! Wheee!', mood: 'excited' },
  'fizz.walk': { speaker: 'fizz', text: 'Walking is okay too! Hopping’s my favourite, though.', mood: 'happy' },
  'rowan.cross': { speaker: 'rowan', text: 'Steady as a table. Here comes lunch!', mood: 'excited' },
  'nar.oldBridge': { speaker: 'narrator', text: 'An old log bridge. Its logs rolled off the rocks.', mood: 'thinking' },
  'nar.rollLog': { speaker: 'narrator', text: 'Tap a log to roll it back onto the rocks.', mood: 'happy' },
  'rowan.letsCross': { speaker: 'rowan', text: 'Who wants to try crossing? Tap a friend.', mood: 'happy' },
  'rowan.picnic': { speaker: 'rowan', text: 'Everyone made it! Picnic on the far bank!', mood: 'excited' },
  'nar.flag': { speaker: 'narrator', text: 'Rowan gives you the bridge flag for the clubhouse.', mood: 'happy' },
} satisfies Record<string, Line>;

export const WATER_LINES = {
  'rowan.hook': { speaker: 'rowan', text: 'The waterwheel stopped, and the mill lanterns went dark.', mood: 'worried' },
  'rowan.why': { speaker: 'rowan', text: 'There’s no water coming down. I wonder why?', mood: 'thinking' },
  'nar.explore': { speaker: 'narrator', text: 'Follow the stream uphill. Tap things to look closely.', mood: 'happy' },
  'nar.dryWheel': { speaker: 'narrator', text: 'The channel is dry. Something upstream?', mood: 'thinking' },
  'nar.clueLeaf': { speaker: 'narrator', text: 'A leaf, stuck in the mud. More leaves upstream?', mood: 'thinking' },
  'nar.clueFeet': { speaker: 'narrator', text: 'Wet footprints! Little hoppy ones.', mood: 'surprised' },
  'nar.clueBucket': { speaker: 'narrator', text: 'A bucket full of leaves. Someone was busy!', mood: 'thinking' },
  'fizz.splash': { speaker: 'fizz', text: 'Look at my splash pool! I built a leaf dam!', mood: 'excited' },
  'fizz.oh': { speaker: 'fizz', text: 'Oh. The wheel stopped? That’s my dam. I forgot to tell anyone.', mood: 'embarrassed' },
  'fizz.sorry': { speaker: 'fizz', text: 'I’m sorry. Can I help fix it?', mood: 'embarrassed' },
  'fizz.feel': { speaker: 'fizz', text: 'I feel a bit wobbly inside. I didn’t mean to stop it.', mood: 'worried' },
  'fizz.didntThink': { speaker: 'fizz', text: 'I was so excited, I didn’t think about the wheel.', mood: 'embarrassed' },
  'fizz.together': { speaker: 'fizz', text: 'Together! If we make a side channel, the water can go both ways.', mood: 'determined' },
  'nar.channel': { speaker: 'narrator', text: 'Tap a stone, then tap the channel spot. Fizz takes the other end.', mood: 'happy' },
  'fizz.heave': { speaker: 'fizz', text: 'Heave… ho!', mood: 'determined' },
  'fizz.both': { speaker: 'fizz', text: 'The pool AND the wheel! Best of both!', mood: 'excited' },
  'fizz.okAlone': { speaker: 'fizz', text: 'Okay. I’ll watch. Shout if you want help.', mood: 'calm' },
  'nar.leaves': { speaker: 'narrator', text: 'Tap the leaves to clear the dam.', mood: 'happy' },
  'fizz.poolGone': { speaker: 'fizz', text: 'Bye-bye, pool. That’s okay — the lanterns matter more today.', mood: 'sad' },
  'moss.measure': { speaker: 'moss', text: 'Let me measure. The channel should go… right here.', mood: 'thinking' },
  'moss.marked': { speaker: 'moss', text: 'I marked the spots. Stones go on the marks.', mood: 'happy' },
  'rowan.turning': { speaker: 'rowan', text: 'It’s turning! Listen — splish, clunk, splish!', mood: 'excited' },
  'rowan.lights': { speaker: 'rowan', text: 'The lanterns are on! Thank you, both of you.', mood: 'excited' },
  'rowan.lightsSolo': { speaker: 'rowan', text: 'The lanterns are on! The whole mill is glowing.', mood: 'excited' },
  'nar.wheel': { speaker: 'narrator', text: 'Rowan gives you a little paddle wheel for the clubhouse.', mood: 'happy' },
} satisfies Record<string, Line>;

export const LAUNCH_LINES = {
  'luma.hook': { speaker: 'luma', text: 'Tonight is the lantern launch! Everyone has a job.', mood: 'excited' },
  'luma.pick': { speaker: 'luma', text: 'Which job would you like?', mood: 'happy' },
  'luma.fold': { speaker: 'luma', text: 'Fold the paper along the lines. Tap each line.', mood: 'happy' },
  'rowan.light': { speaker: 'rowan', text: 'Carry the little flame to the lantern. Careful, slow steps!', mood: 'happy' },
  'moss.hold': { speaker: 'moss', text: 'Hold the line and let it out bit by bit. Tap to let out more.', mood: 'calm' },
  'pip.signal': { speaker: 'pip', text: 'Ring the bell three times for the countdown!', mood: 'excited' },
  'fizz.path': { speaker: 'fizz', text: 'The path lanterns need lighting too. A nice quiet job!', mood: 'calm' },
  'nar.othersHelp': { speaker: 'narrator', text: 'Your friends do the other jobs.', mood: 'happy' },
  'nar.ready': { speaker: 'narrator', text: 'Everything is ready. Three… two… one…', mood: 'excited' },
  'nar.wobble': { speaker: 'narrator', text: 'Up… up… wobble… down it comes!', mood: 'surprised' },
  'pip.bonk': { speaker: 'pip', text: 'Boop! It landed on my head. Too heavy?', mood: 'silly' },
  'luma.fixes': { speaker: 'luma', text: 'Hmm. How could we make it lighter, or lift it more?', mood: 'thinking' },
  'luma.trim': { speaker: 'luma', text: 'Snip, snip — less paper, less weight.', mood: 'happy' },
  'rowan.balloon': { speaker: 'rowan', text: 'A second little balloon for extra lift!', mood: 'excited' },
  'luma.swap': { speaker: 'luma', text: 'Let’s swap jobs. I’ll refold it thinner.', mood: 'happy' },
  'nar.again': { speaker: 'narrator', text: 'Let’s try again. Three… two… one…', mood: 'excited' },
  'luma.rise': { speaker: 'luma', text: 'It’s rising! Look at it glow!', mood: 'excited' },
  'nar.sky': { speaker: 'narrator', text: 'One by one, the club’s lanterns fill the sky.', mood: 'calm' },
  'luma.thanks': { speaker: 'luma', text: 'Every job helped. Even the quiet ones.', mood: 'happy' },
  'nar.lantern': { speaker: 'narrator', text: 'A little lantern for the clubhouse, to remember tonight.', mood: 'happy' },
} satisfies Record<string, Line>;

/** Shared endings for every adventure (no teasers, no pressure). */
export const TRAIL_END_LINES = {
  'nar.endChoices': { speaker: 'narrator', text: 'Look around some more, or head somewhere else?', mood: 'happy' },
} satisfies Record<string, Line>;
